# Generated by Django 6.0 on 2025-12-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_remove_tenant_timezone_alter_tenant_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
