# Generated by Django 6.0 on 2025-12-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_tenant_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="default_ready_hour",
            field=models.PositiveSmallIntegerField(default=17),
        ),
        migrations.AddField(
            model_name="tenant",
            name="default_ready_minute",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="default_turnaround_days",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
