# Generated by Django 6.0 on 2025-12-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenant_default_ready_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="require_paid_in_full_at_pickup",
            field=models.BooleanField(default=True),
        ),
    ]
