# Generated by Django 6.0 on 2026-01-22 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_tenant_membership_and_config_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenantconfigevent",
            new_name="tenants_ten_tenant__5cb484_idx",
            old_name="tenants_ten_tenant__4cc1e2_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantmembership",
            new_name="tenants_ten_tenant__76ffb5_idx",
            old_name="tenants_ten_tenant__25c0a8_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantmembership",
            new_name="tenants_ten_tenant__b981b3_idx",
            old_name="tenants_ten_tenant__62f0f1_idx",
        ),
        migrations.AlterField(
            model_name="tenantmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_memberships_v2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
