# Generated by Django 6.0 on 2026-01-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0008_rename_tenants_ten_tenant__4cc1e2_idx_tenants_ten_tenant__5cb484_idx_and_more",
        ),
        ("tenants", "0008_tenant_membership_event"),
    ]

    operations = []
