# Generated by Django 6.0 on 2026-01-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_merge_20260121_1823"),
        ("tenants", "0009_tenant_invites"),
    ]

    operations = []
