# Generated by Django 6.0 on 2026-01-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_merge_0009_merge_20260121_1823_0009_tenant_invites"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenantinvite",
            new_name="tenants_ten_tenant__4640ea_idx",
            old_name="tenants_ten_tenant__8f60d0_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantinvite",
            new_name="tenants_ten_tenant__686425_idx",
            old_name="tenants_ten_tenant__af8ec1_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantinvite",
            new_name="tenants_ten_tenant__3671ac_idx",
            old_name="tenants_ten_tenant__8d2507_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantinviteevent",
            new_name="tenants_ten_tenant__1a2b5c_idx",
            old_name="tenants_ten_tenant__1e0877_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantinviteevent",
            new_name="tenants_ten_tenant__c2cafe_idx",
            old_name="tenants_ten_tenant__2665e9_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantmembershipevent",
            new_name="tenants_ten_tenant__2da026_idx",
            old_name="tenants_ten_tenant__d0b0e8_idx",
        ),
    ]
