# Generated by Django 6.0 on 2025-12-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.PositiveIntegerField()),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("generated_amount_cents", models.PositiveIntegerField(default=0)),
                ("manual_adjustment_cents", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("OTHER", "Other"),
                        ],
                        default="CARD",
                        max_length=10,
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="reports.invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DAILY_SUMMARY", "Daily Summary"),
                            ("WEEKLY_SUMMARY", "Weekly Summary"),
                            ("MONTHLY_SUMMARY", "Monthly Summary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("generated_total_cents", models.PositiveIntegerField(default=0)),
                ("manual_total_cents", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("amount_cents", models.IntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_manual", models.BooleanField(default=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="reports.report",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReportRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edited_by_user_id", models.IntegerField()),
                ("snapshot_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="reports.report",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "issued_at"], name="reports_inv_tenant__318062_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "invoice_number"),
                name="uniq_invoice_number_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "created_at"], name="reports_pay_tenant__304fd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["tenant", "kind", "start_date", "end_date"],
                name="reports_rep_tenant__19025a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["tenant", "generated_at"], name="reports_rep_tenant__063965_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportline",
            index=models.Index(
                fields=["tenant", "report"], name="reports_rep_tenant__ebb391_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportrevision",
            index=models.Index(
                fields=["tenant", "created_at"], name="reports_rep_tenant__867886_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportrevision",
            index=models.Index(
                fields=["tenant", "report"], name="reports_rep_tenant__8af98a_idx"
            ),
        ),
    ]
