# Generated by Django 6.0 on 2025-12-27 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("tenants", "0002_remove_tenant_timezone_alter_tenant_name_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="orderitem",
            name="orders_orde_tenant__1e7123_idx",
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="uniq_order_number_per_tenant",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_tenant__4de285_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Received"),
                    ("IN_PROCESS", "In process"),
                    ("READY", "Ready"),
                    ("PICKED_UP", "Picked up"),
                    ("CANCELED", "Canceled"),
                ],
                default="RECEIVED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="tenants.tenant",
            ),
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_number",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
