# Generated by Django 6.0 on 2025-12-27 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("orders", "0003_orderitem"),
        ("tenants", "0002_remove_tenant_timezone_alter_tenant_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_tenant__8eff50_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_tenant__291115_idx",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="inventory_item",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="inventory.inventoryitem",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="RECEIVED", max_length=20),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["tenant", "item"], name="orders_orde_tenant__8aa99e_idx"
            ),
        ),
    ]
