# Generated by Django 6.0 on 2025-12-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid_cents",
            field=models.IntegerField(default=0),
        ),
    ]
