# Generated by Django 6.0 on 2025-12-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_paid_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
