# Generated by Django 6.0 on 2025-12-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_settled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="settled_balance_due_cents",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="settled_change_cents",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="settled_paid_cents",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="settled_total_cents",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
