# Generated by Django 6.0 on 2025-12-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_orderstatusevent_order_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="picked_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
