# Generated by Django 6.0 on 2025-12-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_phone_e164_and_more"),
        ("orders", "0009_order_picked_up_at"),
        ("tenants", "0003_alter_tenant_slug"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "status", "ready_at"],
                name="orders_orde_tenant__d8eae4_idx",
            ),
        ),
    ]
