# Generated by Django 6.0 on 2026-01-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_note"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ordernote",
            new_name="orders_orde_tenant__c78104_idx",
            old_name="orders_orde_tenant__order__created_idx",
        ),
    ]
