# Generated by Django 6.0 on 2026-02-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0005_rename_customers_cus_tenant__phone_idx_customers_c_tenant__6d2a04_idx_and_more",
        ),
        (
            "orders",
            "0013_rename_orders_orde_tenant__order__created_idx_orders_orde_tenant__c78104_idx",
        ),
        ("tenants", "0014_tenant_order_tag_print_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="storage_assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=80)),
                ("rack_number", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_locations",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="storage_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.storagelocation",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "storage_location"],
                name="orders_orde_tenant__adafc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storagelocation",
            index=models.Index(
                fields=["tenant", "barcode"], name="orders_stor_tenant__fb049e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storagelocation",
            index=models.Index(
                fields=["tenant", "rack_number"], name="orders_stor_tenant__e60868_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storagelocation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "barcode"),
                name="uniq_storage_location_tenant_barcode",
            ),
        ),
    ]
