# Generated by Django 6.0 on 2025-12-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_options_and_more"),
        ("tenants", "0003_alter_tenant_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_e164",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "phone_e164"], name="customers_c_tenant__10fcc0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_e164", ""), _negated=True),
                fields=("tenant", "phone_e164"),
                name="uniq_customer_phone_per_tenant",
            ),
        ),
    ]
