# Generated by Django 6.0 on 2026-01-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_update_fields_and_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customer",
            new_name="customers_c_tenant__6d2a04_idx",
            old_name="customers_cus_tenant__phone_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="customers_c_tenant__0aea56_idx",
            old_name="customers_cus_tenant__email_idx",
        ),
    ]
