# Generated by Django 6.0 on 2025-12-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_remove_tenant_timezone_alter_tenant_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sku", models.CharField(blank=True, max_length=40)),
                ("unit_price_cents", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "name"], name="inventory_i_tenant__3dceaf_idx"
                    ),
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="inventory_i_tenant__904858_idx",
                    ),
                ],
                "unique_together": {("tenant", "name")},
            },
        ),
    ]
