# Generated by Django 5.2.6 on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
