# Generated by Django 6.0 on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventoryitem_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="inventory_items/"),
        ),
    ]
