# Generated by Django 6.0 on 2026-02-12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_inventoryitem_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="image_url",
        ),
    ]
