# Generated by Django 6.0 on 2025-12-27 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0005_alter_order_paid_cents"),
        ("tenants", "0002_remove_tenant_timezone_alter_tenant_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("ONLINE", "Online"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CAPTURED", "Captured"), ("VOIDED", "Voided")],
                        default="CAPTURED",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "In"), ("OUT", "Out")],
                        default="IN",
                        max_length=3,
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_payments",
                        related_query_name="order_payment",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "order"],
                        name="payments_pa_tenant__d3cdd7_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="payments_pa_tenant__acd7cf_idx",
                    ),
                ],
            },
        ),
    ]
