# Generated by Django 6.0 on 2025-12-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_settled_at"),
        ("payments", "0001_initial"),
        ("tenants", "0002_remove_tenant_timezone_alter_tenant_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "reference"], name="payments_pa_tenant__71b5da_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference", ""), _negated=True),
                fields=("tenant", "reference"),
                name="uniq_payment_reference_per_tenant_nonempty",
            ),
        ),
    ]
