# Generated by Django 6.0 on 2025-12-28 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_settled_at"),
        ("payments", "0002_alter_payment_note_alter_payment_reference_and_more"),
        ("tenants", "0002_remove_tenant_timezone_alter_tenant_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("REFUND", "Refund"),
                            ("CHARGEBACK", "Chargeback"),
                            ("WRITE_OFF", "Write-off"),
                            ("CREDIT_APPLIED", "Credit applied"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("APPLIED", "Applied"), ("VOIDED", "Voided")],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "In"), ("OUT", "Out")],
                        default="OUT",
                        max_length=3,
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("reference", models.CharField(blank=True, max_length=120, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_adjustments",
                        related_query_name="order_adjustment",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "order"],
                        name="payments_ad_tenant__b6e482_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="payments_ad_tenant__b886b1_idx",
                    ),
                    models.Index(
                        fields=["tenant", "reference"],
                        name="payments_ad_tenant__443a38_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            models.Q(("reference", ""), _negated=True),
                            models.Q(("reference__isnull", True), _negated=True),
                        ),
                        fields=("tenant", "reference"),
                        name="uniq_adjustment_reference_per_tenant_nonempty",
                    )
                ],
            },
        ),
    ]
