# Generated by Django 6.0 on 2025-12-29 21:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0005_tenant_require_paid_in_full_at_pickup"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("USER", "User"), ("SYSTEM", "System")],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "actor_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("action", models.CharField(max_length=80)),
                ("entity_type", models.CharField(max_length=40)),
                ("entity_id", models.CharField(max_length=64)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="audit_audit_tenant__290b62_idx",
                    ),
                    models.Index(
                        fields=["tenant", "request_id"],
                        name="audit_audit_tenant__e9ce8e_idx",
                    ),
                    models.Index(
                        fields=["tenant", "entity_type", "entity_id", "created_at"],
                        name="audit_audit_tenant__4f5bd6_idx",
                    ),
                    models.Index(
                        fields=["tenant", "action", "created_at"],
                        name="audit_audit_tenant__126ade_idx",
                    ),
                ],
            },
        ),
    ]
